insert into person (id, first_name, last_name, email, gender, country) values (1, 'Lonnie', 'Shervington', 'lshervington0@ebay.com', 'Female', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, country) values (2, 'Emlyn', 'Parmiter', 'eparmiter1@creativecommons.org', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, country) values (3, 'Justina', 'Marzellano', 'jmarzellano2@oaic.gov.au', 'Female', 'Zambia');
insert into person (id, first_name, last_name, email, gender, country) values (4, 'Jon', 'Blackader', 'jblackader3@businessweek.com', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, country) values (5, 'Grannie', 'Bushaway', 'gbushaway4@about.me', 'Male', 'France');
insert into person (id, first_name, last_name, email, gender, country) values (6, 'Thain', 'Chisholme', 'tchisholme5@trellian.com', 'Male', 'Argentina');
insert into person (id, first_name, last_name, email, gender, country) values (7, 'Gradeigh', 'Nuscha', 'gnuscha6@utexas.edu', 'Male', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, country) values (8, 'Clem', 'Pierri', 'cpierri7@icio.us', 'Male', 'Poland');
insert into person (id, first_name, last_name, email, gender, country) values (9, 'Hermine', 'Ohrtmann', 'hohrtmann8@delicious.com', 'Female', 'Peru');
insert into person (id, first_name, last_name, email, gender, country) values (10, 'Blair', 'Tunnadine', 'btunnadine9@amazon.com', 'Male', 'Marshall Islands');
